version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - coffee_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coffee
    ports:
      - "5432:5432"
    networks:
      - coffee_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - coffee_network

  celery:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
    env_file:
      - .env
    networks:
      - coffee_network

  celery-beat:
    build: .
    command: celery -A app.core.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
    env_file:
      - .env
    networks:
      - coffee_network

networks:
  coffee_network:

volumes:
  postgres_data:
